### ISSUE TITLE
text.html not working

### ISSUE THREAD

**Issue by lunabeille** [lunabeille/pmp#3]
The current .html file isn't working when you open it in a browser.
I think it might be the same bug than for the lulu version.

**Comment by mchelin** [comment]
Do you have a "bower_components" directory in the project directory ? and  a "bower" link in src dir ? 

-> if no, you probably didnt run the "make" command, in  the project directory (juste type "make", it will install external libs -- jquery, requirejs -- through bower). Let me know if you have troubles during this step. 

-> if yes, can you please give me these informations, in order to reproduce the bug on my side ? 
- browser + version (can be seen in "about" menu) 
- js errors displayed in your browser console, if you have some ? (ctrl + shift + i to display console. see errors in the "console" tab)

thanks!

**Comment by lunabeille** [comment]
i did run the make command ;)
and i do have a bower_components dir in the project main directory. i have a bower link in the same dir, not the src.. should i move it there ?

**Comment by mchelin** [comment]
ok, its a bug. Link must be done in src directory, not in main directory. My bad, fixin it.

**Comment by mchelin** [comment]
fixed now. Lulu can you validate and close, please ?
